name: Build VST
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CMake
        uses: jfrog/setup-cmake@v1
      - name: Configure
        run: cmake -B build -S .
      - name: Build
        run: cmake --build build --config Release
      - name: Upload VST
        uses: actions/upload-artifact@v3
        with:
          name: AudioToMidiVST-Binary
          path: build/AudioToMidiVST/*.vst3
